### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by mehdinz** [zecaptus/react-native-animated-transition#1]
Could you please help me
issue message:
undefined is not an object (evaluating '_react2.proptypes.func')

**Comment by nitinsh99** [comment]
There is an issue with this library. In all the js files of this library you need to import prop types form the dedicated bundle instead of React. Like following:

import PropTypes from 'prop-types';

This will resolve the issue. Hope author fixes this. Also, Once this is fixed I don't see the animation though on android. Works fine on iOS :/

**Comment by zecaptus** [comment]
Hello,
This is an old library, this was done before facebook thought to split proptype in an other library.
I don't really have time to update this, now.

I'm ok if someone can send a PR. 
Btw I will use this animation for a side project, so I planned to update it for the next month I guess.

**Comment by zecaptus** [comment]
PropTypes updated.

@nitinsh99  
For android bug, open another issue.
